// Viable scheduler states
export const SCHEDULE_NOT_CREATED = "SCHEDULE_NOT_CREATED";
export const SCHEDULE_IN_PROGRESS = "SCHEDULE_VOTING_IN_PROGRESS";
export const SCHEDULE_DATE_SELECTED = "SCHEDULE_DATE_SELECTED";
